
import "./home.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sessionwrapper from "@/components/sessionwrapper";

export const metadata = {
  title: "Madhyamed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Sessionwrapper>
        <Navbar/>
        {children}
        <Footer/>
        </Sessionwrapper>
      </body>
    </html>
  );
}
